### PR TITLE
Revert "Temporarily disable boot from volume test"

### PR DESCRIPTION
**Pull request by fnordahl**
This reverts commit 289fe6766385977f99c6ab45bf7432114ba67a27.

### CODE REVIEW

**Comment by fnordahl** [comment]
@ChrisMacNaughton if you feel the tests have settled now and agree that the issue we saw a few weeks back was due to something else, let's enable it again.

**Comment by ChrisMacNaughton** [comment]
Has this been tested to be working now? I'd hate to re-enable the boot from volume test just to re-disable it a few days later because it's blocking specs

**Comment by fnordahl** [comment]
Fair question, I'll do and document a extended test run

**Comment by fnordahl** [comment]
Need to confirm this will not break the specs before merging, closing for now and will re-open when confirmed.

**Pull request closed without merging**
